defmodule WebUi.Iur.InterpreterTest do
  use ExUnit.Case, async: true

  alias UnifiedIUR.Layouts
  alias UnifiedIUR.Style
  alias UnifiedIUR.Widgets
  alias WebUi.Iur.Interpreter
  alias WebUi.TypedError

  test "interprets nested vbox/hbox trees with deterministic ids and widget inventory" do
    spec = %{
      type: :vbox,
      id: :root_layout,
      spacing: 2,
      children: [
        %{
          type: :button,
          id: :save_button,
          label: "Save",
          on_click: :save
        },
        %{
          type: :hbox,
          children: [
            %{
              type: :text_input,
              id: :name_input,
              value: "",
              on_change: :name_changed,
              on_submit: {:submit_name, %{source: "profile_form"}}
            }
          ]
        }
      ]
    }

    assert {:ok, interpreted} = Interpreter.interpret(spec, correlation_id: "corr-iur-001")
    assert interpreted.root.type == :layout
    assert interpreted.root.kind == "vbox"
    assert interpreted.root.id == "root_layout"
    assert interpreted.root.props.spacing == 2

    assert Enum.map(interpreted.widgets, & &1.widget_id) == ["save_button", "name_input"]
    assert Enum.map(interpreted.widgets, & &1.widget_kind) == ["button", "text_input"]

    assert Enum.map(interpreted.signals, & &1.source_field) == [
             "on_click",
             "on_change",
             "on_submit"
           ]

    assert Enum.map(interpreted.signals, & &1.widget_id) == [
             "save_button",
             "name_input",
             "name_input"
           ]

    assert Enum.map(interpreted.events, & &1.type) == [
             "unified.button.clicked",
             "unified.input.changed",
             "unified.form.submitted"
           ]

    assert Enum.at(interpreted.events, 0).data.action == "save"
    assert Enum.at(interpreted.events, 1).data.widget_id == "name_input"
    assert Enum.at(interpreted.events, 2).data.action == "submit_name"
  end

  test "supports map inputs with string keys and autogenerated ids" do
    spec = %{
      "type" => "hbox",
      "children" => [
        %{"type" => "text", "content" => "Hello"},
        %{"type" => "button", "label" => "Run", "on_click" => %{"action" => "run"}}
      ]
    }

    assert {:ok, interpreted} = Interpreter.interpret(spec)

    assert interpreted.root.id == "hbox_root"
    assert Enum.map(interpreted.widgets, & &1.widget_kind) == ["label", "button"]
    assert Enum.map(interpreted.widgets, & &1.widget_id) == ["text_0", "button_1"]
    assert length(interpreted.signals) == 1
    assert Enum.map(interpreted.events, & &1.type) == ["unified.button.clicked"]
    assert hd(interpreted.events).data.action == "run"
  end

  test "maps atom, map, and tuple signals into canonical event payloads" do
    spec = %{
      type: :vbox,
      children: [
        %{type: :button, id: :run_button, on_click: :run},
        %{type: :button, id: :stop_button, on_click: %{"action" => "stop"}},
        %{type: :text_input, id: :query_input, on_submit: {:search, %{source: "header"}}}
      ]
    }

    assert {:ok, interpreted} = Interpreter.interpret(spec)

    assert Enum.map(interpreted.events, & &1.type) == [
             "unified.button.clicked",
             "unified.button.clicked",
             "unified.form.submitted"
           ]

    assert Enum.at(interpreted.events, 0).data.action == "run"
    assert Enum.at(interpreted.events, 1).data.action == "stop"
    assert Enum.at(interpreted.events, 2).data.action == "search"
    assert Enum.at(interpreted.events, 2).data.form_id == "query_input"
  end

  test "fails closed when layout children are not a list" do
    spec = %{type: :vbox, id: :invalid_layout, children: %{type: :button}}

    assert {:error, %TypedError{} = error} =
             Interpreter.interpret(spec, correlation_id: "corr-iur-002")

    assert error.error_code == "iur.interpreter.invalid_children"
    assert error.correlation_id == "corr-iur-002"
  end

  test "fails closed when element type cannot be inferred" do
    spec = %{id: :missing_type}

    assert {:error, %TypedError{} = error} = Interpreter.interpret(spec)
    assert error.error_code == "iur.interpreter.unknown_element_type"
  end

  test "normalizes canonical UnifiedIUR structs with deterministic signal mapping" do
    spec = %Layouts.VBox{
      id: :root_layout,
      spacing: 1,
      children: [
        %Widgets.Button{id: :save_button, label: "Save", on_click: :save},
        %Widgets.TextInput{
          id: :name_input,
          value: "",
          on_change: :name_changed,
          on_submit: {:submit_name, %{source: "profile_form"}}
        }
      ]
    }

    assert {:ok, interpreted} = Interpreter.interpret(spec)

    assert interpreted.root.type == :layout
    assert interpreted.root.kind == "vbox"
    assert interpreted.root.id == "root_layout"
    assert interpreted.root.props.spacing == 1
    assert Enum.map(interpreted.widgets, & &1.widget_id) == ["save_button", "name_input"]

    assert Enum.map(interpreted.events, & &1.type) == [
             "unified.button.clicked",
             "unified.input.changed",
             "unified.form.submitted"
           ]
  end

  test "fails closed for unsupported schema source markers" do
    spec = %{
      type: :button,
      id: :save_button,
      on_click: :save,
      schema: "unified_iur",
      schema_source: "unknown/repo"
    }

    assert {:error, %TypedError{} = error} =
             Interpreter.interpret(spec, correlation_id: "corr-iur-source-001")

    assert error.error_code == "iur.interpreter.unsupported_schema_source"
    assert error.correlation_id == "corr-iur-source-001"
  end

  test "maps canonical extended menu/table/tabs/tree signals deterministically" do
    spec = %Layouts.VBox{
      id: :extended_root,
      children: [
        %Widgets.Menu{
          id: :main_menu,
          items: [
            %Widgets.MenuItem{id: :open_item, label: "Open", action: "open_file"}
          ]
        },
        %Widgets.Table{
          id: :orders_table,
          data: [],
          columns: [],
          on_row_select: %{row_index: 2},
          on_sort: %{column: "price", direction: "asc"}
        },
        %Widgets.Tabs{
          id: :main_tabs,
          active_tab: :overview,
          on_change: %{tab_id: "details"},
          tabs: [
            %Widgets.Tab{id: :overview, label: "Overview"},
            %Widgets.Tab{id: :details, label: "Details"}
          ]
        },
        %Widgets.TreeView{
          id: :nav_tree,
          root_nodes: [
            %Widgets.TreeNode{id: :node_1, label: "Node 1", expanded: false}
          ],
          on_select: %{node_id: "node-1"},
          on_toggle: %{node_id: "node-1", expanded: true}
        }
      ]
    }

    assert {:ok, interpreted} = Interpreter.interpret(spec)

    assert Enum.map(interpreted.events, & &1.type) == [
             "unified.menu.action_selected",
             "unified.table.row_selected",
             "unified.table.sorted",
             "unified.tab.changed",
             "unified.tree.node_selected",
             "unified.tree.node_toggled"
           ]

    assert Enum.at(interpreted.events, 0).data.action_id == "open_file"
    assert Enum.at(interpreted.events, 1).data.row_index == 2
    assert Enum.at(interpreted.events, 2).data.column == "price"
    assert Enum.at(interpreted.events, 2).data.direction == "asc"
    assert Enum.at(interpreted.events, 3).data.tab_id == "details"
    assert Enum.at(interpreted.events, 4).data.node_id == "node-1"
    assert Enum.at(interpreted.events, 5).data.expanded == true

    menu_node = Enum.find(interpreted.root.children, &(&1.id == "main_menu"))
    open_item_node = Enum.find(menu_node.children, &(&1.id == "open_item"))
    table_node = Enum.find(interpreted.root.children, &(&1.id == "orders_table"))
    tabs_node = Enum.find(interpreted.root.children, &(&1.id == "main_tabs"))
    tree_node = Enum.find(interpreted.root.children, &(&1.id == "nav_tree"))

    refute Map.has_key?(open_item_node.props, :action)
    refute Map.has_key?(table_node.props, :on_row_select)
    refute Map.has_key?(table_node.props, :on_sort)
    refute Map.has_key?(tabs_node.props, :on_change)
    refute Map.has_key?(tree_node.props, :on_select)
    refute Map.has_key?(tree_node.props, :on_toggle)

    widget_ids = Enum.map(interpreted.widgets, & &1.widget_id)
    assert "main_menu" in widget_ids
    assert "open_item" in widget_ids
    assert "orders_table" in widget_ids
    assert "main_tabs" in widget_ids
    assert "overview" in widget_ids
    assert "details" in widget_ids
    assert "nav_tree" in widget_ids
    assert "node_1" in widget_ids
  end

  test "coerces canonical extended signal payload atoms and string indexes deterministically" do
    spec = %{
      type: :vbox,
      id: :extended_root,
      children: [
        %{
          type: :menu,
          id: :main_menu,
          children: [
            %{type: :menu_item, id: :open_item, label: "Open", action: :open_file}
          ]
        },
        %{
          type: :table,
          id: :orders_table,
          on_row_select: %{index: "3"},
          on_sort: %{column: :price, direction: :DESC}
        },
        %{
          type: :tabs,
          id: :main_tabs,
          on_change: %{tab_id: :details}
        },
        %{
          type: :tree_view,
          id: :nav_tree,
          on_select: %{node_id: :node_1},
          on_toggle: %{node_id: :node_1, expanded: "true"}
        }
      ]
    }

    assert {:ok, interpreted} = Interpreter.interpret(spec)

    assert Enum.map(interpreted.events, & &1.type) == [
             "unified.menu.action_selected",
             "unified.table.row_selected",
             "unified.table.sorted",
             "unified.tab.changed",
             "unified.tree.node_selected",
             "unified.tree.node_toggled"
           ]

    assert Enum.at(interpreted.events, 0).data.action_id == "open_file"
    assert Enum.at(interpreted.events, 1).data.row_index == 3
    assert Enum.at(interpreted.events, 2).data.column == "price"
    assert Enum.at(interpreted.events, 2).data.direction == "desc"
    assert Enum.at(interpreted.events, 3).data.tab_id == "details"
    assert Enum.at(interpreted.events, 4).data.node_id == "node_1"
    assert Enum.at(interpreted.events, 5).data.node_id == "node_1"
    assert Enum.at(interpreted.events, 5).data.expanded == true
  end

  test "normalizes canonical extended struct and map inputs to identical descriptor trees" do
    struct_spec = %Layouts.VBox{
      id: :extended_root,
      children: [
        %Widgets.Menu{
          id: :main_menu,
          items: [
            %Widgets.MenuItem{id: :open_item, label: "Open", action: "open_file"}
          ]
        },
        %Widgets.Table{
          id: :orders_table,
          data: [],
          columns: [],
          on_row_select: %{row_index: 2},
          on_sort: %{column: "price", direction: "asc"}
        },
        %Widgets.Tabs{
          id: :main_tabs,
          active_tab: :overview,
          on_change: %{tab_id: "details"},
          tabs: [
            %Widgets.Tab{id: :overview, label: "Overview"},
            %Widgets.Tab{id: :details, label: "Details"}
          ]
        },
        %Widgets.TreeView{
          id: :nav_tree,
          root_nodes: [
            %Widgets.TreeNode{id: :node_1, label: "Node 1", expanded: false}
          ],
          on_select: %{node_id: "node-1"},
          on_toggle: %{node_id: "node-1", expanded: true}
        }
      ]
    }

    map_spec = %{
      type: :vbox,
      id: :extended_root,
      children: [
        %{
          type: :menu,
          id: :main_menu,
          children: [
            %{type: :menu_item, id: :open_item, label: "Open", action: "open_file"}
          ]
        },
        %{
          type: :table,
          id: :orders_table,
          data: [],
          columns: [],
          on_row_select: %{row_index: 2},
          on_sort: %{column: "price", direction: "asc"}
        },
        %{
          type: :tabs,
          id: :main_tabs,
          active_tab: :overview,
          on_change: %{tab_id: "details"},
          children: [
            %{type: :tab, id: :overview, label: "Overview"},
            %{type: :tab, id: :details, label: "Details"}
          ]
        },
        %{
          type: :tree_view,
          id: :nav_tree,
          on_select: %{node_id: "node-1"},
          on_toggle: %{node_id: "node-1", expanded: true},
          children: [
            %{type: :tree_node, id: :node_1, label: "Node 1", expanded: false}
          ]
        }
      ]
    }

    assert {:ok, interpreted_struct} = Interpreter.interpret(struct_spec)
    assert {:ok, interpreted_map} = Interpreter.interpret(map_spec)

    assert interpreted_struct.root == interpreted_map.root
    assert interpreted_struct.widgets == interpreted_map.widgets
    assert interpreted_struct.signals == interpreted_map.signals
    assert interpreted_struct.events == interpreted_map.events
  end

  test "normalizes canonical nested style values from struct and map inputs identically" do
    struct_spec = %Layouts.VBox{
      id: :styled_root,
      children: [
        %Widgets.Button{
          id: :save_button,
          label: "Save",
          on_click: :save,
          style: %Style{fg: :blue, attrs: [:bold]}
        }
      ]
    }

    map_spec = %{
      type: :vbox,
      id: :styled_root,
      children: [
        %{
          type: :button,
          id: :save_button,
          label: "Save",
          on_click: :save,
          style: %{"fg" => :blue, "attrs" => [:bold]}
        }
      ]
    }

    assert {:ok, interpreted_struct} = Interpreter.interpret(struct_spec)
    assert {:ok, interpreted_map} = Interpreter.interpret(map_spec)

    assert interpreted_struct.root == interpreted_map.root
    assert interpreted_struct.widgets == interpreted_map.widgets
    assert interpreted_struct.signals == interpreted_map.signals
    assert interpreted_struct.events == interpreted_map.events
  end

  test "normalizes canonical nested table column defaults from struct and map inputs identically" do
    struct_spec = %Layouts.VBox{
      id: :nested_defaults_root,
      children: [
        %Widgets.Table{
          id: :orders_table,
          data: [%{id: 1, total: 99}],
          columns: [
            %Widgets.Column{key: :id, header: "ID"}
          ],
          on_row_select: %{row_index: 0},
          on_sort: %{column: "id", direction: "asc"}
        }
      ]
    }

    map_spec = %{
      type: :vbox,
      id: :nested_defaults_root,
      children: [
        %{
          type: :table,
          id: :orders_table,
          data: [%{"id" => 1, "total" => 99}],
          columns: [
            %{"key" => :id, "header" => "ID"}
          ],
          on_row_select: %{row_index: 0},
          on_sort: %{column: "id", direction: "asc"}
        }
      ]
    }

    assert {:ok, interpreted_struct} = Interpreter.interpret(struct_spec)
    assert {:ok, interpreted_map} = Interpreter.interpret(map_spec)

    assert interpreted_struct.root == interpreted_map.root
    assert interpreted_struct.widgets == interpreted_map.widgets
    assert interpreted_struct.signals == interpreted_map.signals
    assert interpreted_struct.events == interpreted_map.events
  end

  test "normalizes canonical expanded_nodes MapSet and list inputs identically" do
    struct_spec = %Layouts.VBox{
      id: :tree_root,
      children: [
        %Widgets.TreeView{
          id: :nav_tree,
          expanded_nodes: MapSet.new([:node_2, :node_1]),
          root_nodes: [
            %Widgets.TreeNode{id: :node_1, label: "Node 1"},
            %Widgets.TreeNode{id: :node_2, label: "Node 2"}
          ],
          on_select: %{node_id: "node-1"}
        }
      ]
    }

    map_spec = %{
      type: :vbox,
      id: :tree_root,
      children: [
        %{
          type: :tree_view,
          id: :nav_tree,
          expanded_nodes: [:node_1, :node_2],
          children: [
            %{type: :tree_node, id: :node_1, label: "Node 1"},
            %{type: :tree_node, id: :node_2, label: "Node 2"}
          ],
          on_select: %{node_id: "node-1"}
        }
      ]
    }

    assert {:ok, interpreted_struct} = Interpreter.interpret(struct_spec)
    assert {:ok, interpreted_map} = Interpreter.interpret(map_spec)

    assert interpreted_struct.root == interpreted_map.root
    assert interpreted_struct.widgets == interpreted_map.widgets
    assert interpreted_struct.signals == interpreted_map.signals
    assert interpreted_struct.events == interpreted_map.events
  end

  test "fails closed for malformed canonical extended signal payloads" do
    spec = %{
      type: :vbox,
      children: [
        %{type: :table, id: :orders_table, on_sort: %{column: "price", direction: "sideways"}}
      ]
    }

    assert {:error, %TypedError{} = error} =
             Interpreter.interpret(spec, correlation_id: "corr-iur-extended-err")

    assert error.error_code == "iur.interpreter.signal_mapping_failed"
    assert error.correlation_id == "corr-iur-extended-err"
  end
end
