defmodule UnifiedUi.Dsl.Node do
  @moduledoc """
  Baseline authored node shape for `UnifiedUi` widgets, forms, and layouts.
  """

  @type family :: :foundational | :input | :navigation | :forms | :layout

  @type t :: %__MODULE__{
          __identifier__: atom() | nil,
          id: atom() | nil,
          family: family() | nil,
          kind: atom() | nil,
          value: String.t() | nil,
          label: String.t() | nil,
          target: String.t() | atom() | nil,
          source: String.t() | nil,
          name: atom() | String.t() | nil,
          description: String.t() | nil,
          authored_ref: [atom()] | nil,
          annotations: keyword(),
          tags: [atom()],
          variant: atom() | nil,
          tone: atom() | nil,
          style_refs: [atom()],
          accessibility_label: String.t() | nil,
          accessibility_description: String.t() | nil,
          action_intent: atom() | nil,
          navigation_target: String.t() | nil,
          disabled?: boolean(),
          set: atom() | nil,
          fallback_text: String.t() | nil,
          alt_text: String.t() | nil,
          media_type: String.t() | nil,
          fit: atom() | nil,
          role: atom() | nil,
          presentation: atom() | nil,
          summary: String.t() | nil,
          emphasis: atom() | nil,
          external?: boolean() | nil,
          target_kind: atom() | nil,
          orientation: atom() | nil,
          decorative?: boolean() | nil,
          size: atom() | nil,
          grow: integer() | nil,
          placeholder: String.t() | nil,
          multiline?: boolean() | nil,
          input_mode: atom() | nil,
          options: keyword(),
          active_item: atom() | nil,
          multiple?: boolean() | nil,
          field_name: atom() | nil,
          value_path: [atom()] | nil,
          default_value: term(),
          submit_intent: atom() | nil,
          legend: String.t() | nil,
          help: String.t() | nil,
          gap: atom() | integer() | nil,
          align: atom() | nil,
          justify: atom() | nil,
          width: integer() | atom() | nil,
          height: integer() | atom() | nil,
          columns: integer() | nil,
          rows: integer() | nil,
          children: [t()]
        }

  defstruct __identifier__: nil,
            id: nil,
            family: nil,
            kind: nil,
            value: nil,
            label: nil,
            target: nil,
            source: nil,
            name: nil,
            description: nil,
            authored_ref: nil,
            annotations: [],
            tags: [],
            variant: nil,
            tone: nil,
            style_refs: [],
            accessibility_label: nil,
            accessibility_description: nil,
            action_intent: nil,
            navigation_target: nil,
            disabled?: false,
            set: nil,
            fallback_text: nil,
            alt_text: nil,
            media_type: nil,
            fit: nil,
            role: nil,
            presentation: nil,
            summary: nil,
            emphasis: nil,
            external?: nil,
            target_kind: nil,
            orientation: nil,
            decorative?: nil,
            size: nil,
            grow: nil,
            placeholder: nil,
            multiline?: nil,
            input_mode: nil,
            options: [],
            active_item: nil,
            multiple?: nil,
            field_name: nil,
            value_path: nil,
            default_value: nil,
            submit_intent: nil,
            legend: nil,
            help: nil,
            gap: nil,
            align: nil,
            justify: nil,
            width: nil,
            height: nil,
            columns: nil,
            rows: nil,
            children: []

  @spec summary(t()) :: map()
  def summary(%__MODULE__{} = node) do
    %{
      id: node.id,
      family: node.family,
      kind: node.kind,
      value: node.value,
      label: node.label,
      target: node.target,
      source: node.source,
      role: node.role,
      presentation: node.presentation,
      summary: node.summary,
      children: Enum.map(node.children, &summary/1)
    }
    |> Enum.reject(fn {_key, value} -> value in [nil, []] end)
    |> Enum.into(%{})
  end
end
