defmodule UnifiedUi.Dsl.Node do
  @moduledoc """
  Baseline authored node shape for `UnifiedUi` widgets, forms, and layouts.
  """

  @type family ::
          :foundational
          | :input
          | :navigation
          | :forms
          | :layout
          | :data
          | :feedback
          | :advanced
          | :overlay
          | :display
          | :canvas
          | :content_identity_and_disclosure

  @type t :: %__MODULE__{
          __identifier__: atom() | nil,
          id: atom() | nil,
          family: family() | nil,
          kind: atom() | nil,
          value: term(),
          label: String.t() | nil,
          target: String.t() | atom() | nil,
          source: String.t() | nil,
          name: atom() | String.t() | nil,
          eyebrow: String.t() | nil,
          description: String.t() | nil,
          authored_ref: [atom()] | nil,
          annotations: keyword(),
          tags: [atom()],
          variant: atom() | nil,
          tone: atom() | nil,
          theme_ref: atom() | nil,
          style_refs: [atom()],
          style: UnifiedUi.Style.t() | nil,
          interaction_refs: [atom()],
          binding_refs: [atom()],
          accessibility_label: String.t() | nil,
          accessibility_description: String.t() | nil,
          action_intent: atom() | nil,
          navigation_target: String.t() | nil,
          disabled?: boolean(),
          set: atom() | nil,
          fallback_text: String.t() | nil,
          alt_text: String.t() | nil,
          media_type: String.t() | nil,
          fit: atom() | nil,
          role: atom() | nil,
          presentation: atom() | nil,
          summary: String.t() | nil,
          emphasis: atom() | nil,
          external?: boolean() | nil,
          target_kind: atom() | nil,
          orientation: atom() | nil,
          decorative?: boolean() | nil,
          size: atom() | nil,
          grow: integer() | nil,
          placeholder: String.t() | nil,
          multiline?: boolean() | nil,
          input_mode: atom() | nil,
          min: term(),
          max: term(),
          step: term(),
          format: atom() | nil,
          accept: [String.t()] | nil,
          capture: String.t() | nil,
          options: keyword(),
          active_item: atom() | nil,
          multiple?: boolean() | nil,
          field_name: atom() | nil,
          value_path: [atom()] | nil,
          default_value: term(),
          submit_intent: atom() | nil,
          legend: String.t() | nil,
          help: String.t() | nil,
          gap: atom() | integer() | nil,
          align: atom() | nil,
          justify: atom() | nil,
          width: integer() | atom() | nil,
          height: integer() | atom() | nil,
          columns: integer() | nil,
          rows: integer() | nil,
          items: list() | nil,
          ordered?: boolean() | nil,
          selection_mode: atom() | nil,
          table_columns: keyword() | list() | nil,
          table_rows: list() | nil,
          empty_state: String.t() | nil,
          tree_nodes: list() | nil,
          log_entries: list() | nil,
          show_timestamps?: boolean() | nil,
          wrap?: boolean() | nil,
          severity: atom() | nil,
          status: atom() | nil,
          current: integer() | float() | nil,
          minimum: integer() | float() | nil,
          maximum: integer() | float() | nil,
          indeterminate?: boolean() | nil,
          points: list() | nil,
          series: list() | nil,
          x_label: String.t() | nil,
          y_label: String.t() | nil,
          entries: list() | nil,
          ordering: atom() | nil,
          severity_field: atom() | nil,
          timestamp_field: atom() | nil,
          processes: list() | nil,
          sort_by: atom() | nil,
          topology: list() | nil,
          expanded?: boolean() | nil,
          cluster_nodes: list() | nil,
          metrics: map() | nil,
          title: String.t() | nil,
          message: String.t() | nil,
          content_ref: atom() | nil,
          target_ref: atom() | nil,
          trigger_ref: atom() | nil,
          visible?: boolean() | nil,
          modal?: boolean() | nil,
          confirm_intent: atom() | nil,
          dismiss_intent: atom() | nil,
          placement: atom() | nil,
          base_ref: atom() | nil,
          layer_refs: [atom()] | nil,
          background_fill: atom() | nil,
          position: integer() | nil,
          viewport_size: integer() | nil,
          content_size: integer() | nil,
          offset: term(),
          clip?: boolean() | nil,
          x: integer() | nil,
          y: integer() | nil,
          z_index: integer() | nil,
          primary_ref: atom() | nil,
          secondary_ref: atom() | nil,
          ratio: float() | nil,
          divider_size: integer() | nil,
          divider_style: atom() | nil,
          operations: list() | nil,
          level: atom() | nil,
          segments: list() | nil,
          separator: String.t() | nil,
          initials: String.t() | nil,
          image_source: String.t() | nil,
          shape: atom() | nil,
          state: atom() | nil,
          open?: boolean() | nil,
          children: [t()]
        }

  defstruct __identifier__: nil,
            id: nil,
            family: nil,
            kind: nil,
            value: nil,
            label: nil,
            target: nil,
            source: nil,
            name: nil,
            eyebrow: nil,
            description: nil,
            authored_ref: nil,
            annotations: [],
            tags: [],
            variant: nil,
            tone: nil,
            theme_ref: nil,
            style_refs: [],
            style: nil,
            interaction_refs: [],
            binding_refs: [],
            accessibility_label: nil,
            accessibility_description: nil,
            action_intent: nil,
            navigation_target: nil,
            disabled?: false,
            set: nil,
            fallback_text: nil,
            alt_text: nil,
            media_type: nil,
            fit: nil,
            role: nil,
            presentation: nil,
            summary: nil,
            emphasis: nil,
            external?: nil,
            target_kind: nil,
            orientation: nil,
            decorative?: nil,
            size: nil,
            grow: nil,
            placeholder: nil,
            multiline?: nil,
            input_mode: nil,
            min: nil,
            max: nil,
            step: nil,
            format: nil,
            accept: nil,
            capture: nil,
            options: [],
            active_item: nil,
            multiple?: nil,
            field_name: nil,
            value_path: nil,
            default_value: nil,
            submit_intent: nil,
            legend: nil,
            help: nil,
            gap: nil,
            align: nil,
            justify: nil,
            width: nil,
            height: nil,
            columns: nil,
            rows: nil,
            items: nil,
            ordered?: nil,
            selection_mode: nil,
            table_columns: nil,
            table_rows: nil,
            empty_state: nil,
            tree_nodes: nil,
            log_entries: nil,
            show_timestamps?: nil,
            wrap?: nil,
            severity: nil,
            status: nil,
            current: nil,
            minimum: nil,
            maximum: nil,
            indeterminate?: nil,
            points: nil,
            series: nil,
            x_label: nil,
            y_label: nil,
            entries: nil,
            ordering: nil,
            severity_field: nil,
            timestamp_field: nil,
            processes: nil,
            sort_by: nil,
            topology: nil,
            expanded?: nil,
            cluster_nodes: nil,
            metrics: nil,
            title: nil,
            message: nil,
            content_ref: nil,
            target_ref: nil,
            trigger_ref: nil,
            visible?: nil,
            modal?: nil,
            confirm_intent: nil,
            dismiss_intent: nil,
            placement: nil,
            base_ref: nil,
            layer_refs: nil,
            background_fill: nil,
            position: nil,
            viewport_size: nil,
            content_size: nil,
            offset: nil,
            clip?: nil,
            x: nil,
            y: nil,
            z_index: nil,
            primary_ref: nil,
            secondary_ref: nil,
            ratio: nil,
            divider_size: nil,
            divider_style: nil,
            operations: nil,
            level: nil,
            segments: nil,
            separator: nil,
            initials: nil,
            image_source: nil,
            shape: nil,
            state: nil,
            open?: nil,
            children: []

  @spec summary(t()) :: map()
  def summary(%__MODULE__{} = node) do
    %{
      id: node.id,
      family: node.family,
      kind: node.kind,
      value: node.value,
      label: node.label,
      target: node.target,
      source: node.source,
      eyebrow: node.eyebrow,
      variant: node.variant,
      tone: node.tone,
      theme_ref: node.theme_ref,
      style_refs: node.style_refs,
      style:
        case node.style do
          nil -> nil
          style -> UnifiedUi.Style.summary(style)
        end,
      interaction_refs: node.interaction_refs,
      binding_refs: node.binding_refs,
      role: node.role,
      presentation: node.presentation,
      summary: node.summary,
      items: node.items,
      ordered?: node.ordered?,
      selection_mode: node.selection_mode,
      empty_state: node.empty_state,
      severity: node.severity,
      status: node.status,
      title: node.title,
      message: node.message,
      content_ref: node.content_ref,
      target_ref: node.target_ref,
      trigger_ref: node.trigger_ref,
      placement: node.placement,
      base_ref: node.base_ref,
      layer_refs: node.layer_refs,
      background_fill: node.background_fill,
      position: node.position,
      viewport_size: node.viewport_size,
      content_size: node.content_size,
      offset: node.offset,
      clip?: node.clip?,
      x: node.x,
      y: node.y,
      z_index: node.z_index,
      primary_ref: node.primary_ref,
      secondary_ref: node.secondary_ref,
      ratio: node.ratio,
      operations: node.operations,
      level: node.level,
      segments: node.segments,
      separator: node.separator,
      initials: node.initials,
      image_source: node.image_source,
      shape: node.shape,
      state: node.state,
      open?: node.open?,
      current: node.current,
      minimum: node.minimum,
      maximum: node.maximum,
      indeterminate?: node.indeterminate?,
      x_label: node.x_label,
      y_label: node.y_label,
      ordering: node.ordering,
      severity_field: node.severity_field,
      timestamp_field: node.timestamp_field,
      sort_by: node.sort_by,
      expanded?: node.expanded?,
      children: Enum.map(node.children, &summary/1)
    }
    |> Enum.reject(fn {_key, value} -> value in [nil, []] end)
    |> Enum.into(%{})
  end
end
